CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE food (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    price INTEGER NOT NULL,
    image VARCHAR(100) NOT NULL
);
